Book_Store/Areas/Admin/Controllers/AdminPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Book_Store.Models;
using PagedList.Core;
using NToastNotify;
using Book_Store.Helpper;
using Book_Store.Areas.Admin.Models.Authentication;

namespace Book_Store.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authentication]
    public class AdminPostsController : Controller
    {
        private readonly BookManagementContext _context;
        private readonly IToastNotification _toastNotification;

        public AdminPostsController(BookManagementContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }

        // GET: Admin/AdminPosts
        public IActionResult Index(int? page)
        {
            var collection = _context.Posts.AsNoTracking().ToList();
            foreach (var item in collection)
            {
                if (item.CreateDate == null)
                {
                    item.CreateDate = DateTime.Now;
                    _context.Update(item);
                    _context.SaveChanges();
                }
            }

            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lsPosts = _context.Posts
                .AsNoTracking()
                .OrderBy(x => x.PostId);
            PagedList<Post> models = new PagedList<Post>(lsPosts, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Account)
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Admin/AdminPosts/Create
        public IActionResult Create()
        {
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId");
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName");
            return View();
        }

        // POST: Admin/AdminPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreateDate,Author,AccountId,Tags,CateId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] Post post, Microsoft.AspNetCore.Http.IFormFile? fThumb)
        {
            if (ModelState.IsValid)
            {
                //Xu ly Thumb
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(post.Title) + extension;
                    post.Thumb = await Utilities.UploadFile(fThumb, @"news", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(post.Thumb)) post.Thumb = "default.jpg";
                post.Alias = Utilities.SEOUrl(post.Title);
                post.CreateDate = DateTime.Now;


                _context.Add(post);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", post.AccountId);
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", post.CateId);
            return View(post);
        }

        // GET: Admin/AdminPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", post.AccountId);
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", post.CateId);
            return View(post);
        }

        // POST: Admin/AdminPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreateDate,Author,AccountId,Tags,CateId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] Post post, Microsoft.AspNetCore.Http.IFormFile? fThumb)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Xu ly Thumb
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(post.Title) + extension;
                        post.Thumb = await Utilities.UploadFile(fThumb, @"news", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(post.Thumb)) post.Thumb = "default.jpg";
                    post.Alias = Utilities.SEOUrl(post.Title);

                    _context.Update(post);
                    await _context.SaveChangesAsync();
                    _toastNotification.AddSuccessToastMessage("Chỉnh sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", post.AccountId);
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", post.CateId);
            return View(post);
        }

        // GET: Admin/AdminPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Account)
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Admin/AdminPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'QlBansachContext.Posts'  is null.");
            }
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }
            
            await _context.SaveChangesAsync();
            _toastNotification.AddSuccessToastMessage("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
          return (_context.Posts?.Any(e => e.PostId == id)).GetValueOrDefault();
        }
    }
}

Book_Store/Areas/Admin/Views/AdminPosts/Create.cshtml
@model Book_Store.Models.Post

@{ ViewData["Title"] = "Tạo mới tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminPosts" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Tạo mới tin</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminPosts" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-plus-circle"></i>
                    <span>Tạo mới tin tức</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="IsHot" type="checkbox" />
                                <label for="IsHot">IsHot</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="IsNewfeed" type="checkbox" />
                                <label for="IsNewfeed">IsNewfeed</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

Book_Store/Areas/Admin/Views/AdminPosts/Delete.cshtml
@model Book_Store.Models.Post

@{
    ViewData["Title"] = "Xóa tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminPosts" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Xóa tin tức: @Model.Title</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/news/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">Post Images</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">THÔNG TIN TIN TỨC : @Model.Title</h4>
                    <div class="table-responsive">
                        <form asp-action="Delete" asp-route-id="@Model.PostId">
                            <input type="hidden" asp-for="PostId" />
                            <table class="product-info-table m-t-20">
                                <tbody>
                                    <tr>
                                        <td>Tiêu đề:</td>
                                        <td class="text-dark font-weight-semibold">@Model.Title</td>
                                    </tr>
                                    <tr>
                                        <td>Ngày tạo:</td>
                                        <td>@Model.CreateDate</td>
                                    </tr>
                                    <tr>
                                        <td>Alias:</td>
                                        <td>@Model.Alias</td>
                                    </tr>
                                    <tr>
                                        <td>Trạng Thái:</td>
                                        <td>
                                            <div class="check-box">
                                                <input asp-for="Published" type="checkbox" disabled>
                                                <label for="Published">Public</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>HOT:</td>
                                        <td>
                                            <div class="check-box">
                                                <input asp-for="IsHot" type="checkbox" disabled>
                                                <label for="IsHot">HOT</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>New Feed:</td>
                                        <td>
                                            <div class="check-box">
                                                <input asp-for="IsNewfeed" type="checkbox" disabled>
                                                <label for="IsNewfeed">NewFeed</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Xác nhận xóa:</td>
                                        <td>
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">THÔNG TIN MÔ TẢ</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="img-fluid" src="~/images/news/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Book_Store/Areas/Admin/Views/AdminPosts/Details.cshtml
@model Book_Store.Models.Post

@{ ViewData["Title"] = "Chi tiết tin tức: " + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminPosts" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Chi tiết tin tức: @Model.Title</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/news/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminPosts" asp-action="Edit" asp-route-id="@Model.PostId">Edit</a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">Post Images</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">THÔNG TIN TIN TỨC : @Model.Title</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>Tiêu đề:</td>
                                    <td class="text-dark font-weight-semibold">@Model.Title</td>
                                </tr>
                                <tr>
                                    <td>Ngày tạo:</td>
                                    <td>@Model.CreateDate</td>
                                </tr>
                                <tr>
                                    <td>Alias:</td>
                                    <td>@Model.Alias</td>
                                </tr>
                                <tr>
                                    <td>Trạng Thái:</td>
                                    <td>
                                        <div class="check-box">
                                            <input asp-for="Published" type="checkbox" disabled>
                                            <label for="Published">Public</label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>HOT:</td>
                                    <td>
                                        <div class="check-box">
                                            <input asp-for="IsHot" type="checkbox" disabled>
                                            <label for="IsHot">HOT</label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>New Feed:</td>
                                    <td>
                                        <div class="check-box">
                                            <input asp-for="IsNewfeed" type="checkbox" disabled>
                                            <label for="IsNewfeed">NewFeed</label>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">THÔNG TIN MÔ TẢ</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="img-fluid" src="~/images/news/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Book_Store/Areas/Admin/Views/AdminPosts/Edit.cshtml
@model Book_Store.Models.Post

@{ ViewData["Title"] = "Chỉnh sửa tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminPosts" asp-action="Index" class="breadcrumb-item">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Chỉnh sửa : @Model.Title</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminPosts" asp-action="Edit" asp-route-id="@Model.PostId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PostId" />
    <input type="hidden" asp-for="Thumb" />
    <input type="hidden" asp-for="CreateDate" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu thay đổi</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="IsHot" type="checkbox" />
                                <label for="IsHot">IsHot</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="IsNewfeed" type="checkbox" />
                                <label for="IsNewfeed">IsNewfeed</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}